version: '3.3'
services:
  client-backend:
    image: ru.dsluchenko.appointment-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/appointments
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  service-db:
    image: postgres:15.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_DB=appointments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
